name: Build & Deploy Spring Boot App

on:
  push:
    paths:
      - 'app/**'

jobs:
  build-and-deploy:
    uses: jcontreras549/devsecops_template/.github/workflows/ci-cd-java.yml@main
    permissions:
      contents: read
    secrets: inherit
    # with:
    #   aws_region: us-east-1
    #   docker_image_name: app01
    #   docker_image_tag: 1.0.0
    #   ecr_repository_name: app01
    #   eks_cluster_name: my-eks-cluster
    #   kubectl_config_path: ./kubeconfig
    #   helm_chart_path: ./helm-chart
    #   helm_release_name: app01-release
