name: Provision Infrastructure

on:
  push:
    paths:
      - 'infra/**'

jobs:
  build-and-deploy:
    uses: jcontreras549/devsecops_template/.github/workflows/terraform_provisioning.yml@main
    permissions:
      contents: read
    secrets: inherit
    with:
      destroy: true