name: Provision Infrastructure

on:
  push:
    paths:
      - 'infra/**'

  workflow_dispatch:
    inputs:
      destroy:
        description: 'Run destroy?'
        required: true
        default: false
        type: boolean

jobs:
  build-and-deploy:
    uses: jcontreras549/devsecops_template/.github/workflows/terraform_provisioning.yml@main
    permissions:
      contents: read
    secrets: inherit
    with:
      destroy: true